### ISSUE TITLE
Integrate TaDiRAH

### ISSUE THREAD

**Issue by tillgrallert** [FuReSH/tool-storage-metadata#11]
Da es im Moment noch keine Möglichkeit gibt die Klassifizierung von Werkzeugen mit Hilfe von TaDiRAH direkt in Wikidata vorzunehmen, brauchen wir einen temporären Workaround. Das könnte heißen, dass wir die Klassifizierung direkt in unserem YAML vornehmen und z.B. auch wieder über JSON Schema validieren lassen

```yml
classification:
  - vocabulary: URI ("https://vocabs.dariah.eu/tadirah/")
    code:
      - URI: "https://vocabs.dariah.eu/tadirah/opticalCharacterRecognition"
      - URI: "https://vocabs.dariah.eu/tadirah/webScraping"
```

**Comment by sopheck** [comment]
Wir haben die TaDiRAH-Klassifizierung bei den blackboxes auch mit drin, allerdings auf einer allgemeineren 2. Ebene: `tadirah-broader-concept` (archiving, gathering...). Die Frage ist daher, wie wir TaDiRAH bei uns integrieren wollen. Ein Vorschlag wäre, dass wir die Tools auf der untersten Ebene klassifizieren und Blackboxes dann allgemeiner auf der 2. Ebene.
Beispiel Blackbox:
```yaml
name: webscraping.blackbox
tadirah-broader-concept:
  - archiving
  - gathering
  - ...
```
 

Beispiel Tool:
```yaml
name: snscrape.tool
tadirah-closer-concept:
  - opticalCharacterRecognition
  - webScraping
  - ...
```
